### ISSUE TITLE
Unsafe mapping of a ruleResult's `cfg` property

### ISSUE THREAD

**Issue by rtkay123** [tazama-lf/rule-executer#190]
https://github.com/frmscoe/rule-executer/blob/a8c95801900c305b5b46e75867c58ece1f924d65/src/controllers/execute.ts#L68-L79

May throw an exception if the `request` object does not follow that structure.

For example, I ran a later version of the rule executor with a version of the network map that still had channels. That code block, was not happy as I was trying to iterate on an undefined property.

There's a default of empty string, `''` if the `cfg` was not found, perhaps that could also be used when an exception is thrown?

## Acceptance criteria
1. Recreate and verify error handling makes sense

**Comment by rtkay123** [comment]
Cannot reproduce.

Old (Tazama 1.0) Network Map gets called out by event-director, which logs the problem.

**Comment by Justus-at-Tazama** [comment]
@rtkay123 - I see this was dropped in the QA bucket - anything specific you want us to do here?

**Comment by rtkay123** [comment]
I couldn't reproduce the issue. Either `event-director` caught the error or this processor reports it back.

The platform has to be in a very particular state for this to happen and I cannot get that to align. I recall this issue affecting you as well, any ideas on how I can trigger it?
